import { useEffect, useState } from "react";
import { Link } from "react-router";
import { api } from "../helpers/http-client";

import Swal from "sweetalert2";

function Profile() {
  const [profile, setProfile] = useState({
    name: "",
    age: "",
    personalHistory: "",
    familyHistory: "",
    foodAllergy: "",
    drugAllergy: "",
    recommendation: "",
  });

  const fetchProfile = async () => {
    try {
      const response = await api.get("/ip/profile", {
        headers: {
          Authorization: `Bearer ${localStorage.getItem("access_token")}`,
        },
      });
      setProfile(response.data);
      localStorage.setItem("profile", JSON.stringify(response.data));
    } catch (error) {
      console.log(error);
      Swal.fire({
        icon: "error",
        title: "Failed to fetch profile",
        text: `${error.response.data.message}`,
      });
    }
  };

  useEffect(() => {
    fetchProfile();
  }, []);

  return (
    <div>
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-lg p-6">
          <div className="flex justify-between items-center mb-6">
            <h1 className="text-3xl font-bold text-gray-800">Profile</h1>
            <Link
              to="/editprofile"
              className="bg-teal-600 text-white px-4 py-2 rounded-md hover:bg-teal-700 transition">
              Edit Profile
            </Link>
          </div>

          <div className="grid md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <div>
                <h2 className="text-lg font-semibold text-gray-700">Name</h2>
                <p className="text-gray-600">{profile.name}</p>
              </div>
              <div>
                <h2 className="text-lg font-semibold text-gray-700">Age</h2>
                <p className="text-gray-600">{profile.age}</p>
              </div>
              <div>
                <h2 className="text-lg font-semibold text-gray-700">
                  Personal History
                </h2>
                <p className="text-gray-600">{profile.personalHistory}</p>
              </div>
              <div>
                <h2 className="text-lg font-semibold text-gray-700">
                  Family History
                </h2>
                <p className="text-gray-600">{profile.familyHistory}</p>
              </div>
            </div>

            <div className="space-y-4">
              <div>
                <h2 className="text-lg font-semibold text-gray-700">
                  Food Allergy
                </h2>
                <p className="text-gray-600">{profile.foodAllergy}</p>
              </div>
              <div>
                <h2 className="text-lg font-semibold text-gray-700">
                  Drug Allergy
                </h2>
                <p className="text-gray-600">{profile.drugAllergy}</p>
              </div>
            </div>
          </div>

          <div className="mt-8">
            <h2 className="text-lg font-semibold text-gray-700 mb-4">
              Recommendation
            </h2>
            <div className="bg-gray-50 p-4 rounded-md">
              <p className="text-gray-600 whitespace-pre-line">
                {profile.recommendation}
              </p>
              <p className="text-sm text-teal-500 mt-4">
                Generated By Perplexity AI
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default Profile;
